#!/bin/bash

echo "画像保存先のフォルダ名入力してください"
read folder_name

mkdir $folder_name
cd $folder_name

echo "ほしい画像の検索ワードを入力してください"
read photo
echo "ページ数を入力してください（1ページ画像30~40枚)くらい？"
read num


i=0

while [ $i -lt $((num)) ];
do
	wget -r -nd -H -e robots=off -A jpg,png -l 1 "http://www.heso.blue/?text=$photo&page=$((i + 1))"
	i=$(( i + 1 ))
done
